DEBUG 2024-09-11 14:32:27,027 nvd_client Cache is invalid: No cache found.
DEBUG 2024-09-11 14:32:27,822 nvd_client Fetched 50 vulnerabilities from API.
DEBUG 2024-09-11 14:32:27,823 nvd_client Data fetched from API. Cache updated.
DEBUG 2024-09-11 14:32:29,955 nvd_client Cache is valid.
DEBUG 2024-09-11 14:32:29,955 nvd_client Data retrieved from cache.
DEBUG 2024-09-11 14:40:31,245 nvd_client Cache is invalid: No cache found.
DEBUG 2024-09-11 14:40:33,155 nvd_client Fetched 50 vulnerabilities from API.
DEBUG 2024-09-11 14:40:33,156 nvd_client Data fetched from API. Cache updated.
DEBUG 2024-09-11 14:53:38,209 nvd_client Cache is invalid: No cache found.
DEBUG 2024-09-11 14:54:04,631 nvd_client Cache is invalid: No cache found.
DEBUG 2024-09-11 14:54:06,911 nvd_client Fetched 50 vulnerabilities from API.
DEBUG 2024-09-11 14:54:06,911 nvd_client Data fetched from API. Cache updated.
DEBUG 2024-09-11 14:54:08,554 nvd_client Fetched 50 vulnerabilities from API.
DEBUG 2024-09-11 14:54:08,555 nvd_client Data fetched from API. Cache updated.
INFO 2024-09-11 14:54:14,831 vulnerability_repository Successfully retrieved all fixed vulnerabilities.
WARNING 2024-09-11 14:54:14,837 vulnerability_service No fixed vulnerabilities retrieved from the repository.
INFO 2024-09-11 14:54:24,741 vulnerability_repository Successfully retrieved all fixed vulnerabilities.
WARNING 2024-09-11 14:54:24,746 vulnerability_service No fixed vulnerabilities retrieved from the repository.
DEBUG 2024-09-11 14:54:38,406 nvd_client Cache is valid.
DEBUG 2024-09-11 14:54:38,406 nvd_client Vulnerability dsdd existence check: False
ERROR 2024-09-11 14:54:38,406 vulnerability_service Error adding vulnerabilities to fixed list or sending alerts: Vulnerability with Id: dsdd does not exists in NIST data base
Traceback (most recent call last):
  File "/app/apps/vulnerabilities/services/vulnerability_service.py", line 139, in add_to_fixed_vulnerabilities
    raise ValueError(
ValueError: Vulnerability with Id: dsdd does not exists in NIST data base
ERROR 2024-09-11 14:54:38,411 vulnerability_views Error marking vulnerabilities as fixed: Vulnerability with Id: dsdd does not exists in NIST data base
Traceback (most recent call last):
  File "/app/apps/vulnerabilities/views/vulnerability_views.py", line 104, in post
    service.add_to_fixed_vulnerabilities(serializer.validated_data)
  File "/app/apps/vulnerabilities/services/vulnerability_service.py", line 139, in add_to_fixed_vulnerabilities
    raise ValueError(
ValueError: Vulnerability with Id: dsdd does not exists in NIST data base
DEBUG 2024-09-11 14:54:50,965 nvd_client Cache is valid.
DEBUG 2024-09-11 14:54:50,965 nvd_client Vulnerability CVE-1999-0095 existence check: True
INFO 2024-09-11 14:54:51,137 vulnerability_repository Successfully added a new fixed vulnerability with ID CVE-1999-0095.
INFO 2024-09-11 14:54:51,282 vulnerability_observer Alert sent to admin@example.com with message: The vulnerability CVE-1999-0095 has been fixed.
DEBUG 2024-09-11 14:54:57,377 nvd_client Cache is valid.
DEBUG 2024-09-11 14:54:57,378 nvd_client Data retrieved from cache.
DEBUG 2024-09-11 14:55:00,709 nvd_client Cache is valid.
DEBUG 2024-09-11 14:55:00,709 nvd_client Data retrieved from cache.
INFO 2024-09-11 14:55:00,709 vulnerability_repository Successfully retrieved all fixed vulnerabilities.
DEBUG 2024-09-11 14:55:07,849 nvd_client Cache is valid.
DEBUG 2024-09-11 14:55:07,849 nvd_client Data retrieved from cache.
DEBUG 2024-09-11 14:55:10,479 nvd_client Cache is valid.
DEBUG 2024-09-11 14:55:10,479 nvd_client Data retrieved from cache.
